In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1,5,6,100,85])               # creates 1D array.
print(arr_1d)                                   # print array.

[  1   5   6 100  85]


In [3]:
type(arr_1d)                                 # Array type: whether its a numpy array or python list.

numpy.ndarray

In [4]:
arr_1d.ndim                                  # dimension of the array.

1

In [10]:
arr_1d.size                                 # size of array = total no. of elements in the array.

5

In [20]:
arr_1d.shape            # shape prints a tuple having no. of elements equal to its dimension,
                        # if dimension = 1 than it prints a single no. corresponding to the no. of element in the array.

(5,)

In [14]:
arr_1d.dtype                                  # data type of the elements present in the array.

dtype('int32')

In [5]:
arr_2d = np.array([[1,4,1,5],[1,8,10,9],[2,3,6,7]])                  # creates 2D array.
print(arr_2d)

[[ 1  4  1  5]
 [ 1  8 10  9]
 [ 2  3  6  7]]


In [9]:
type(arr_2d)

numpy.ndarray

In [8]:
arr_2d.ndim

2

In [11]:
arr_2d.size

12

In [13]:
arr_2d.shape             # shape prints a tuple having no. of elements equal to its dimension,
                        # if dimension = 2 than it prints 2 numbers representing rows and columns.
                       # (rows,columns)

(3, 4)

In [15]:
arr_2d.dtype

dtype('int32')

In [16]:
arr_2d_2 = np.array([[1],[8],[2]])
print(arr_2d_2)

[[1]
 [8]
 [2]]


In [18]:
arr_2d_2.ndim

2

In [19]:
arr_2d_2.shape

(3, 1)

In [21]:
arr_1d_2 = np.array(["aman","dev","manish","gaurav"])
arr_1d_2.dtype

dtype('<U6')

In [23]:
arr_1d_3 = np.array([0.12,8.36,9,6.00])
arr_1d_3.dtype

dtype('float64')

In [24]:
arr_3d = np.array([[[8,9,6],[1,2,3],[4,5,6]],                         
                  [[5,9,3],[9,3,1],[8,7,4]],                             # creates 2D array.
                  [[5,9,3],[9,3,1],[8,7,4]]])
print(arr_3d)

[[[8 9 6]
  [1 2 3]
  [4 5 6]]

 [[5 9 3]
  [9 3 1]
  [8 7 4]]

 [[5 9 3]
  [9 3 1]
  [8 7 4]]]


In [26]:
arr_3d.ndim

3

In [27]:
arr_3d.shape              # shape prints a tuple having no. of elements equal to its dimension,
                        # if dimension = 3 than it prints 3 numbers representing no.of matrix, rows and columns.
                       # (no. of matrix,rows,columns)

(3, 3, 3)

In [29]:
arr_1d_4 = np.array([1,"aman",0.32,"a"])
print(arr_1d_4)

['1' 'aman' '0.32' 'a']


In [30]:
arr_1d_4.dtype

dtype('<U11')

In [36]:
arr_3d_2 = np.array([[[8,9,6],[1,2,3],[4,5,6]],                         
                  [[5,9,3],[9,3,1],[8,7,4]]])                             # creates 2D array.
print(arr_3d_2)

[[[8 9 6]
  [1 2 3]
  [4 5 6]]

 [[5 9 3]
  [9 3 1]
  [8 7 4]]]


In [37]:
arr_3d_2.shape                        # (no. of matrix,rows,columns)

(2, 3, 3)

In [38]:
arr_3d_3 = np.array([[[8,9,6],[1,2,3]],                         
                  [[5,9,3],[9,3,1]]])                             # creates 2D array.
print(arr_3d_3)

[[[8 9 6]
  [1 2 3]]

 [[5 9 3]
  [9 3 1]]]


In [39]:
arr_3d_3.shape                        # (no. of matrix,rows,columns)

(2, 2, 3)