In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,1,1],[1,1,1],[1,1,1]])                # creating one's array manually.
print(arr1)                                                

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [3]:
arr2 = np.ones(5)                               # creating one's array by function.
print(arr2)

[1. 1. 1. 1. 1.]


In [4]:
arr3 = np.ones((6,3))          # Signature: np.ones(shape, dtype=None, order='C').
                              # Docstring:Return a new array of given shape and type, filled with ones.
print(arr3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
arr4 = np.ones((4,5), dtype=str,)
print(arr4)

[['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']]


In [8]:
arr5 = np.ones((4,5), dtype=int)
print(arr5)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [28]:
arr6 = np.ones((4,5,3), dtype=int)
print(arr6)

[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]


In [29]:
arr7 = np.ones((2,2,2,2), dtype=int)
print(arr7)

[[[[1 1]
   [1 1]]

  [[1 1]
   [1 1]]]


 [[[1 1]
   [1 1]]

  [[1 1]
   [1 1]]]]


In [11]:
arr8 = np.ones((4,5), dtype=int, order='F')                   # by default order ='C'             
print(arr8)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [17]:
arr_0_1 = np.zeros(5)                                       # creates zeroes matrix
print(arr_0_1)

[0. 0. 0. 0. 0.]


In [18]:
arr_0_2 = np.zeros((3,6))                    # Signature: np.ones(shape, dtype=None, order='C').
print(arr_0_2)                              # Docstring:Return a new array of given shape and type, filled with zeroes.

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [19]:
arr_0_3 = np.zeros((3,6), dtype=int)
print(arr_0_3)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [20]:
arr_0_4 = np.zeros((3,6), dtype=str)
print(arr_0_4)

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


In [22]:
arr_0_5 = np.zeros((3,6), dtype=bool)
print(arr_0_5)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [23]:
arr_0_5 = np.ones((3,6), dtype=bool)
print(arr_0_5)

[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]


In [25]:
str1 = ''
str2 = '1'
print(bool(str1))
print(bool(str2))

False
True


In [27]:
arr_emp1 = np.empty((2,4,5))
print(arr_emp1)

[[[            nan 4.94065646e-324 5.71139887e-321 1.97626258e-323
   4.84184333e-321]
  [2.03060980e-321 4.62445445e-321 2.03060980e-321 3.93276254e-321
   2.03060980e-321]
  [3.32012114e-321 4.24399178e-314 2.19365147e-321 2.03060980e-321
   4.48611606e-321]
  [2.03060980e-321 4.05133830e-321 2.03060980e-321 5.71139887e-321
   2.03060980e-321]]

 [[5.71139887e-321 1.97626258e-323             nan             nan
   3.23790862e-319]
  [0.00000000e+000 7.86158284e+121 1.95043360e+224 3.11518555e-307
   1.24610723e-306]
  [9.34608432e-307 1.37959129e-306 8.45596650e-307 1.33511969e-306
   1.12466813e-312]
  [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
   0.00000000e+000]]]


In [30]:
arr_emp2 = np.empty((2,4,5), dtype=int)    # empty(shape, dtype=float, order='C')

                                           # Return a new array of given shape and type, without initializing entries.
print(arr_emp2)

[[[4128860 6029375 3801155 5570652 6619251]
  [7536754 4456540 4980805 6029388 6619204]
  [7012467 7274612 6029424 4259914 5636178]
  [5439561 5046364 6488161 6881384 6619246]]

 [[7077920 6357093 7209074 7209065 6029415]
  [6881340 7929968 6815860 7209071 6881325]
  [7340142 7602293 3276845 2949174 3473458]
  [3211319 6488117 3670066 3604581 3473465]]]
