### Numpy Functions

In [2]:
import numpy as np

#### arange()

In [3]:
# arange([start,] stop[, step,], dtype=None)
arr_1 = np.arange(1,13)
print(arr_1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [5]:
arr_even = np.arange(2,13,2)
print(arr_even)

[ 2  4  6  8 10 12]


In [6]:
arr_odd = np.arange(1,13,2)
print(arr_odd)

[ 1  3  5  7  9 11]


#### linspace()

In [8]:
# np.linspace(start,stop,num=50,endpoint=True,retstep=False,dtype=None,axis=0,)
np.linspace(1,6,4)

array([1.        , 2.66666667, 4.33333333, 6.        ])

#### reshape()

In [10]:
# "array".arange(dimension), dimension or shape = (no. of matrix,rows,columns). 
ar_1d = np.arange(1,13)
ar_2d_1 = ar_1d.reshape(2,6)
print(ar_2d_1)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [11]:
ar_2d_2 = ar_1d.reshape(3,4)
print(ar_2d_2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
ar_3d = ar_1d.reshape(2,2,3)
print(ar_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [15]:
ar = np.arange(10,42,2).reshape(4,4)
print(ar)

[[10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]
 [34 36 38 40]]


In [16]:
ar1 = np.arange(10,42,2).reshape(2,2,4)
print(ar1)

[[[10 12 14 16]
  [18 20 22 24]]

 [[26 28 30 32]
  [34 36 38 40]]]


#### ravel()

In [18]:
# converts to 1D array.
ar1.ravel()

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

#### flatten()

In [19]:
# converts to 1D array.
ar1.flatten()

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

#### transpose()

In [21]:
# changes the dimension or shape of arrays.  changes (3,4,5) to (5,4,3) and (2,10) to (10,2)
ar1.transpose()

array([[[10, 26],
        [18, 34]],

       [[12, 28],
        [20, 36]],

       [[14, 30],
        [22, 38]],

       [[16, 32],
        [24, 40]]])

In [22]:
# Converts rows to columns and columns to rows for 2D arrays.
ar.transpose()

array([[10, 18, 26, 34],
       [12, 20, 28, 36],
       [14, 22, 30, 38],
       [16, 24, 32, 40]])

In [24]:
# 1D remains the same.
ar3 = np.arange(1,7)
ar3.transpose()

array([1, 2, 3, 4, 5, 6])

In [25]:
# also by .T
ar.T

array([[10, 18, 26, 34],
       [12, 20, 28, 36],
       [14, 22, 30, 38],
       [16, 24, 32, 40]])