### Python Numpy Array Concatenation and split

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(8,24).reshape(4,4)
print(arr1)

[[ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [3]:
arr2 = np.arange(1,17).reshape(4,4)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [4]:
list1 = [4,7,8,1]
list2 = [2,7,6,0]

In [5]:
list1 + list2

[4, 7, 8, 1, 2, 7, 6, 0]

In [6]:
arr1 + arr2

array([[ 9, 11, 13, 15],
       [17, 19, 21, 23],
       [25, 27, 29, 31],
       [33, 35, 37, 39]])

In [8]:
np.concatenate((arr1,arr2))

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [9]:
print(arr1)
print(arr2)

[[ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [11]:
np.concatenate((arr1,arr2) ,axis=0)

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [12]:
np.concatenate((arr1,arr2) ,axis=1)

array([[ 8,  9, 10, 11,  1,  2,  3,  4],
       [12, 13, 14, 15,  5,  6,  7,  8],
       [16, 17, 18, 19,  9, 10, 11, 12],
       [20, 21, 22, 23, 13, 14, 15, 16]])

In [14]:
np.vstack((arr1,arr2))

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [15]:
np.hstack((arr1,arr2))

array([[ 8,  9, 10, 11,  1,  2,  3,  4],
       [12, 13, 14, 15,  5,  6,  7,  8],
       [16, 17, 18, 19,  9, 10, 11, 12],
       [20, 21, 22, 23, 13, 14, 15, 16]])

In [16]:
np.hstack((arr1,arr2,arr1))

array([[ 8,  9, 10, 11,  1,  2,  3,  4,  8,  9, 10, 11],
       [12, 13, 14, 15,  5,  6,  7,  8, 12, 13, 14, 15],
       [16, 17, 18, 19,  9, 10, 11, 12, 16, 17, 18, 19],
       [20, 21, 22, 23, 13, 14, 15, 16, 20, 21, 22, 23]])

In [23]:
arr =np.split(arr1,2)
print(arr)

[array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([[16, 17, 18, 19],
       [20, 21, 22, 23]])]


In [18]:
type(arr)

list

In [20]:
arr[0]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
arr[1]

array([[16, 17, 18, 19],
       [20, 21, 22, 23]])

In [22]:
type(arr[1])

numpy.ndarray

In [24]:
np.split(arr1,2, axis=1)

[array([[ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[10, 11],
        [14, 15],
        [18, 19],
        [22, 23]])]

In [26]:
d1 = np.array([2,8,7,1,3])

In [27]:
np.split(d1,[1,3])

[array([2]), array([8, 7]), array([1, 3])]